name: LightBulbs
favicon: null
layout_spectrum: 0.3284767996519804
typography_spectrum: 0.395383721916005
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6964312251657248
  lightness: 0.90968705015257
  saturation: 0.8357941920403391
  rhythmicContrast: 0.5513391359709203
purpose: []
